In [1]:
import numpy as np

a = np.arange(1, 25, 2)
print(a)

[ 1  3  5  7  9 11 13 15 17 19 21 23]


In [ ]:
print("Predicted gap: 5.0")

a = np.linspace(5, 45, 9)
print(a)

Predicted gap: 5.0
[ 5. 10. 15. 20. 25. 30. 35. 40. 45.]


In [ ]:
a = np.arange(1, 10)
b = np.linspace(1, 9, 9)

print(a)
print(a.dtype)

print(b)
print(b.dtype)

[1 2 3 4 5 6 7 8 9]
int64
[1. 2. 3. 4. 5. 6. 7. 8. 9.]
float64


In [ ]:
m = np.eye(6, dtype=int)
print(m)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


In [5]:
m = np.full((3, 4), 5)

print(m)
print(f"Shape: {m.shape}")
print(f"Size: {m.size}")
print(f"ndim: {m.ndim}")

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
Shape: (3, 4)
Size: 12
ndim: 2


In [6]:
import numpy as np

a = np.array([2, 4, 6])
b = np.array([2.0, 4.0, 6.0])

print(f"a: {a.dtype}, b: {b.dtype}")

b = b.astype(int)

print(f"a: {a.dtype}, b: {b.dtype}")
print(f"Match: {a.dtype == b.dtype}")

a: int64, b: float64
a: int64, b: int64
Match: True


In [7]:
import numpy as np

print("Predicted output: [10 25 39]")

a = np.array([10.9, 25.5, 39.99]).astype(int)
print(a)

Predicted output: [10 25 39]
[10 25 39]


In [8]:
import numpy as np

arr = np.arange(10, 101, 10)

print(f"(a) 4th element: {arr[3]}")
print(f"(b) Last element: {arr[-1]}")
print(f"(c) 2nd-last element: {arr[-2]}")

(a) 4th element: 40
(b) Last element: 100
(c) 2nd-last element: 90


In [9]:
import numpy as np

arr = np.arange(10, 101, 10)

print(f"Slice [30 40 50 60]: {arr[2:6]}")
print(f"Reversed array: {arr[::-1]}")

Slice [30 40 50 60]: [30 40 50 60]
Reversed array: [100  90  80  70  60  50  40  30  20  10]


In [ ]:
arr = np.arange(1, 21)
print(arr[1::3])

[ 2  5  8 11 14 17 20]


In [11]:
import numpy as np

arr = np.arange(1, 21)
print(arr[2:-2])

[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


In [ ]:
m = np.array([[ 1,  2,  3,  4,  5],
              [ 6,  7,  8,  9, 10],
              [11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25]])

print("(a) 3rd row:")
print(m[2])

print("\n(b) Last column:")
print(m[:, -1])

print("\n(c) Centre 3x3 block:")
print(m[1:4, 1:4])

(a) 3rd row:
[11 12 13 14 15]

(b) Last column:
[ 5 10 15 20 25]

(c) Centre 3x3 block:
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [ ]:
m = np.array([[ 1,  2,  3,  4,  5],
              [ 6,  7,  8,  9, 10],
              [11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25]])

print(m[::4, ::4])

[[ 1  5]
 [21 25]]


In [ ]:
m = np.array([[ 1,  2,  3,  4,  5],
              [ 6,  7,  8,  9, 10],
              [11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25]])

print(m[::2, ::2])

[[ 1  3  5]
 [11 13 15]
 [21 23 25]]


In [ ]:
marks = np.array([56, 91, 44, 77, 62, 85, 39, 70])

print("(a) Greater than 60:")
print(marks[marks > 60])

print("\n(b) Between 50 and 80:")
print(marks[(marks >= 50) & (marks <= 80)])

(a) Greater than 60:
[91 77 62 85 70]

(b) Between 50 and 80:
[56 77 62 70]
